# Configuration de la source de données MySQL
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/collabInfoDb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: collabuser
    password: collabpassword

  # Dialecte Hibernate pour MySQL
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

        # Crée automatiquement les tables à partir des entités JPA
        hbm2ddl.auto: update

        # Met à jour le schéma de la base de données si nécessaire
        ddl-auto: update

        format_sql: true

    # Afficher les requêtes SQL dans la console (pour le débogage)
    show-sql: true


